# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Raphael Bost
tagline:          'Raphael Bost'
description:      'Ph.D. Candidate'
url:              https://raphael.bost.fyi/

author:
  name:           'Raphael Bost'
  url:            https://raphael.bost.fyi
  institution:	  'Université de Rennes 1'


scholar:
  style: assets/bibliography/acm-siggraph.csl
    
plugins: 
    - 'jekyll-scholar'
    - 'liquefy'

# paginate:         5
# paginate_path: "page:num"
