# Dependencies
markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Raphael Bost
tagline:          'Raphael Bost'
description:      'Ph.D. Candidate'
url:              http://raphael.bost.fyi/

author:
  name:           'Raphael Bost'
  url:            http://raphael.bost.fyi
  institution:	  'Université de Rennes 1'

gems: [jekyll-paginate, jekyll-gist]
# paginate:         5
# paginate_path: "page:num"
